// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var generateTile, ppArray, randomInt, randomValue;
    ppArray = function(array) {
      var row, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        row = array[_i];
        _results.push(console.log(row));
      }
      return _results;
    };
    this.board = [0, 1, 2, 3].map(function() {
      return [0, 1, 2, 3].map(function() {
        return 0;
      });
    });
    ppArray(this.board);
    generateTile = function(board) {};
    randomInt = function() {
      return Math.floor(Math.random() * 3);
    };
    randomValue = function() {
      var val, values;
      values = [2, 2, 2, 4];
      return val = values[randomIndex(values.length) * 3];
    };
    return console.log(values);
  });

}).call(this);

//# sourceMappingURL=main.map
